package co.ipregistry.api.client.model.error;

public enum ErrorCode {

    DISABLED_API_KEY,
    FORBIDDEN_IP,
    FORBIDDEN_ORIGIN,
    INTERNAL,
    INSUFFICIENT_CREDITS,
    INVALID_API_KEY,
    INVALID_FILTER_SYNTAX,
    INVALID_IP_ADDRESS,
    MISSING_API_KEY,
    PRIVATE_IP_ADDRESS,
    TOO_MANY_IPS,
    TOO_MANY_REQUESTS

}
